import jsPDF from "jspdf";
import { sb } from "../lib/supabase";

/**
 * Generates invoices using your custom HTML company template + dynamic data
 */
export async function generateInvoicePDF(data, companyId, type = "invoice") {
  try {
    // Fetch the company profile to get the uploaded HTML invoice_template
    const { data: comp, error } = await sb
      .from("company")
      .select("name, invoice_template")
      .eq("id", companyId)
      .single();

    // If the admin has uploaded a custom HTML template, use it!
    if (!error && comp?.invoice_template) {
      return generateHtmlInvoice(data, comp, type);
    }

    // If no template is uploaded yet, fallback to the basic jsPDF layout
    return generateBasicPDF(data, type);
  } catch (e) {
    console.error("Invoice Generation Error:", e);
    return generateBasicPDF(data, type);
  }
}

/**
 * Replaces placeholders in the HTML template and triggers the PDF Print dialog
 */
function generateHtmlInvoice(data, comp, type) {
  let template = comp.invoice_template;

  // Prepare the dynamic data to inject into the HTML
  // This handles both Deal data and Inventory data
  const replacements = {
    "{{deal_id}}": data.deal_number || data.id || "—",
    "{{date}}": new Date(data.created_at || Date.now()).toLocaleDateString("en-IN"),
    "{{product_name}}": data.product_name || "N/A",
    "{{category}}": data.category || "—",
    "{{wood_type}}": data.wood_type || "—",
    "{{quantity}}": data.quantity || data.available_quantity || 0,
    "{{unit}}": data.unit || "units",
    "{{unit_price}}": (data.negotiated_price || data.cost_price || 0).toLocaleString("en-IN"),
    "{{total_amount}}": (data.total_value || ((data.cost_price || 0) * (data.available_quantity || 0)) || 0).toLocaleString("en-IN"),
    "{{customer_name}}": data.customer_name || "—",
    "{{supplier_name}}": data.supplier_name || "—",
    "{{yard_name}}": data.yard_name || "—",
    "{{company_name}}": comp.name || "Dockside Trade",
  };

  // Replace every placeholder in the HTML with the actual data
  for (const [key, value] of Object.entries(replacements)) {
    // The RegExp with 'g' ensures if you use {{product_name}} twice, both get replaced
    template = template.replace(new RegExp(key, 'g'), value);
  }

  // Open the formatted HTML in a hidden print window
  const printWin = window.open('', '_blank');
  if (!printWin) {
    alert("Popup blocked! Please allow popups to download invoices.");
    return { success: false };
  }
  
  printWin.document.write(template);
  printWin.document.close();
  printWin.focus();
  
  // Wait 500ms for any logos/fonts in the HTML to load, then trigger PDF save
  setTimeout(() => {
    printWin.print();
  }, 500);

  return { success: true };
}

/**
 * Fallback basic PDF generator if no custom HTML is uploaded in Settings
 */
function generateBasicPDF(data, type) {
  const pdf = new jsPDF();

  pdf.setFontSize(18);
  pdf.setFont(undefined, "bold");
  pdf.text("DOCKSIDE TRADE OS", 105, 20, { align: "center" });
  pdf.setFontSize(12);
  pdf.setFont(undefined, "normal");
  pdf.text(type.toUpperCase(), 105, 30, { align: "center" });
  pdf.setLineWidth(0.5);
  pdf.line(20, 35, 190, 35);

  if (data.type === "deal" || data.customer_name) {
    pdf.setFontSize(10);
    pdf.text(`Deal Number: ${data.deal_number || "—"}`, 20, 50);
    pdf.text(`Customer: ${data.customer_name || "—"}`, 20, 60);
    pdf.text(`Product: ${data.product_name || "—"}`, 20, 70);
    pdf.text(`Quantity: ${data.quantity || 0}`, 20, 80);
    pdf.text(`Rate: Rs ${(data.negotiated_price || 0).toLocaleString("en-IN")}`, 20, 90);
    pdf.text(`Total: Rs ${(data.total_value || 0).toLocaleString("en-IN")}`, 20, 100);
    pdf.text(`Payment: ${data.payment_status || "—"}`, 20, 110);
    pdf.text(`Stage: ${data.stage || data.status || "—"}`, 20, 120);
    pdf.text(`Date: ${new Date(data.created_at || Date.now()).toLocaleDateString("en-IN")}`, 20, 130);
  } else {
    pdf.setFontSize(10);
    pdf.text(`Product: ${data.product_name || "—"}`, 20, 50);
    pdf.text(`Category: ${data.category || "—"}`, 20, 60);
    pdf.text(`Wood Type: ${data.wood_type || "—"}`, 20, 70);
    pdf.text(`Grade: ${data.quality_grade || data.grade || "—"}`, 20, 80);
    pdf.text(`Quantity: ${data.available_quantity || 0} ${data.unit || ""}`, 20, 90);
    pdf.text(`Cost: Rs ${(data.cost_price || 0).toLocaleString("en-IN")} per ${data.unit || "unit"}`, 20, 100);
    pdf.text(`Total Value: Rs ${((data.cost_price || 0) * (data.available_quantity || 0)).toLocaleString("en-IN")}`, 20, 110);
    pdf.text(`Yard: ${data.yard_name || "—"}`, 20, 120);
    pdf.text(`Supplier: ${data.supplier_name || "—"}`, 20, 130);
    pdf.text(`Status: ${data.deal_status || "Available"}`, 20, 140);
  }

  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text("Generated by Dockside Trade OS", 105, 280, { align: "center" });
  pdf.text(new Date().toLocaleString("en-IN"), 105, 285, { align: "center" });

  pdf.save(`${type}_${data.product_name || data.customer_name || "document"}_${Date.now()}.pdf`);
  return { success: true };
}

export default { generateInvoicePDF };
